version: '3.8'

services:
  sentiment_predictor:
    build: .
    container_name: sentiment_predictor
    ports:
      - "8501:8501"  
    volumes:
      - sentiment_models:/app/models  
      - sentiment_logs:/app/logs      
      - sentiment_data:/app/data      
    environment:
      - DEVICE=cpu  
    networks:
      - sentiment_net

# Volumes for persistent storage
volumes:
  sentiment_models:
  sentiment_logs:
  sentiment_data:

# Networks for communication between containers
networks:
  sentiment_net:
    driver: bridge
