name: Docker Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.Menegraal }}
          password: ${{ secrets.aivancitymlops }}

      - name: Build Docker image
        run: |
          docker build -t menegraal/sent_predictor:latest .

      - name: Push Docker image to DockerHub
        run: |
          docker push menegraal/sent_predictor:latest
