name: Model Evaluation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  evaluate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.7'

    - name: Load model and evaluate
      run: |
        python evaluation.py  

    - name: Store performance metrics as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: evaluation-metrics
        path: metrics.json

    - name: Fail if performance below threshold
      run: |
        performance=$(python get_performance.py) 
        if (( $(echo "$performance < 0.59" | bc -l) )); fixed 60% as performance threshold
          echo "Performance is below threshold" 
          exit 1
        fi
