name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.7'  # Adjust as necessary for your project

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Run unit and integration tests
      run: |
        pytest  # or use your testing tool, e.g., unittest

    - name: Lint code
      run: |
        pip install flake8
        flake8 .  # Lint the whole codebase
